// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: twitchchat.proto

package twitchchat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusTopics int32

const (
	BusTopics_TRACKSTAR_TWITCH_CHAT_EVENT   BusTopics = 0
	BusTopics_TRACKSTAR_TWITCH_CHAT_REQUEST BusTopics = 1
	BusTopics_TRACKSTAR_TWITCH_CHAT_COMMAND BusTopics = 2
)

// Enum value maps for BusTopics.
var (
	BusTopics_name = map[int32]string{
		0: "TRACKSTAR_TWITCH_CHAT_EVENT",
		1: "TRACKSTAR_TWITCH_CHAT_REQUEST",
		2: "TRACKSTAR_TWITCH_CHAT_COMMAND",
	}
	BusTopics_value = map[string]int32{
		"TRACKSTAR_TWITCH_CHAT_EVENT":   0,
		"TRACKSTAR_TWITCH_CHAT_REQUEST": 1,
		"TRACKSTAR_TWITCH_CHAT_COMMAND": 2,
	}
)

func (x BusTopics) Enum() *BusTopics {
	p := new(BusTopics)
	*p = x
	return p
}

func (x BusTopics) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusTopics) Descriptor() protoreflect.EnumDescriptor {
	return file_twitchchat_proto_enumTypes[0].Descriptor()
}

func (BusTopics) Type() protoreflect.EnumType {
	return &file_twitchchat_proto_enumTypes[0]
}

func (x BusTopics) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusTopics.Descriptor instead.
func (BusTopics) EnumDescriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{0}
}

type MessageTypeRequest int32

const (
	MessageTypeRequest_TRACKSTAR_TWITCH_CHAT_CONFIG_GET_REQ      MessageTypeRequest = 0
	MessageTypeRequest_TRACKSTAR_TWITCH_CHAT_CONFIG_GET_RESP     MessageTypeRequest = 1
	MessageTypeRequest_TRACKSTAR_TWITCH_CHAT_TRACK_ANNOUNCE_REQ  MessageTypeRequest = 2
	MessageTypeRequest_TRACKSTAR_TWITCH_CHAT_TRACK_ANNOUNCE_RESP MessageTypeRequest = 3
)

// Enum value maps for MessageTypeRequest.
var (
	MessageTypeRequest_name = map[int32]string{
		0: "TRACKSTAR_TWITCH_CHAT_CONFIG_GET_REQ",
		1: "TRACKSTAR_TWITCH_CHAT_CONFIG_GET_RESP",
		2: "TRACKSTAR_TWITCH_CHAT_TRACK_ANNOUNCE_REQ",
		3: "TRACKSTAR_TWITCH_CHAT_TRACK_ANNOUNCE_RESP",
	}
	MessageTypeRequest_value = map[string]int32{
		"TRACKSTAR_TWITCH_CHAT_CONFIG_GET_REQ":      0,
		"TRACKSTAR_TWITCH_CHAT_CONFIG_GET_RESP":     1,
		"TRACKSTAR_TWITCH_CHAT_TRACK_ANNOUNCE_REQ":  2,
		"TRACKSTAR_TWITCH_CHAT_TRACK_ANNOUNCE_RESP": 3,
	}
)

func (x MessageTypeRequest) Enum() *MessageTypeRequest {
	p := new(MessageTypeRequest)
	*p = x
	return p
}

func (x MessageTypeRequest) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeRequest) Descriptor() protoreflect.EnumDescriptor {
	return file_twitchchat_proto_enumTypes[1].Descriptor()
}

func (MessageTypeRequest) Type() protoreflect.EnumType {
	return &file_twitchchat_proto_enumTypes[1]
}

func (x MessageTypeRequest) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeRequest.Descriptor instead.
func (MessageTypeRequest) EnumDescriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{1}
}

type MessageTypeCommand int32

const (
	MessageTypeCommand_TRACKSTAR_TWITCH_CHAT_UNSPECIFIED     MessageTypeCommand = 0
	MessageTypeCommand_TRAKCSTAR_TWITCH_CHAT_CONFIG_SET_REQ  MessageTypeCommand = 1
	MessageTypeCommand_TRAKCSTAR_TWITCH_CHAT_CONFIG_SET_RESP MessageTypeCommand = 2
)

// Enum value maps for MessageTypeCommand.
var (
	MessageTypeCommand_name = map[int32]string{
		0: "TRACKSTAR_TWITCH_CHAT_UNSPECIFIED",
		1: "TRAKCSTAR_TWITCH_CHAT_CONFIG_SET_REQ",
		2: "TRAKCSTAR_TWITCH_CHAT_CONFIG_SET_RESP",
	}
	MessageTypeCommand_value = map[string]int32{
		"TRACKSTAR_TWITCH_CHAT_UNSPECIFIED":     0,
		"TRAKCSTAR_TWITCH_CHAT_CONFIG_SET_REQ":  1,
		"TRAKCSTAR_TWITCH_CHAT_CONFIG_SET_RESP": 2,
	}
)

func (x MessageTypeCommand) Enum() *MessageTypeCommand {
	p := new(MessageTypeCommand)
	*p = x
	return p
}

func (x MessageTypeCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageTypeCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_twitchchat_proto_enumTypes[2].Descriptor()
}

func (MessageTypeCommand) Type() protoreflect.EnumType {
	return &file_twitchchat_proto_enumTypes[2]
}

func (x MessageTypeCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageTypeCommand.Descriptor instead.
func (MessageTypeCommand) EnumDescriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{2}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Announce bool   `protobuf:"varint,1,opt,name=announce,proto3" json:"announce,omitempty"`
	Template string `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitchchat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_twitchchat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetAnnounce() bool {
	if x != nil {
		return x.Announce
	}
	return false
}

func (x *Config) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

type ConfigGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigGetRequest) Reset() {
	*x = ConfigGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitchchat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetRequest) ProtoMessage() {}

func (x *ConfigGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twitchchat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetRequest.ProtoReflect.Descriptor instead.
func (*ConfigGetRequest) Descriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{1}
}

type ConfigGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ConfigGetResponse) Reset() {
	*x = ConfigGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitchchat_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetResponse) ProtoMessage() {}

func (x *ConfigGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twitchchat_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigGetResponse) Descriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigGetResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ConfigSetRequest) Reset() {
	*x = ConfigSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitchchat_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetRequest) ProtoMessage() {}

func (x *ConfigSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twitchchat_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetRequest.ProtoReflect.Descriptor instead.
func (*ConfigSetRequest) Descriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigSetRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ConfigSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ConfigSetResponse) Reset() {
	*x = ConfigSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitchchat_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetResponse) ProtoMessage() {}

func (x *ConfigSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twitchchat_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetResponse.ProtoReflect.Descriptor instead.
func (*ConfigSetResponse) Descriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{4}
}

func (x *ConfigSetResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type TrackAnnounceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackAnnounceRequest) Reset() {
	*x = TrackAnnounceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitchchat_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackAnnounceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackAnnounceRequest) ProtoMessage() {}

func (x *TrackAnnounceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_twitchchat_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackAnnounceRequest.ProtoReflect.Descriptor instead.
func (*TrackAnnounceRequest) Descriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{5}
}

type TrackAnnounceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TrackAnnounceResponse) Reset() {
	*x = TrackAnnounceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_twitchchat_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackAnnounceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackAnnounceResponse) ProtoMessage() {}

func (x *TrackAnnounceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_twitchchat_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackAnnounceResponse.ProtoReflect.Descriptor instead.
func (*TrackAnnounceResponse) Descriptor() ([]byte, []int) {
	return file_twitchchat_proto_rawDescGZIP(), []int{6}
}

var File_twitchchat_proto protoreflect.FileDescriptor

var file_twitchchat_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x74, 0x77, 0x69, 0x74, 0x63, 0x68, 0x63, 0x68, 0x61, 0x74, 0x22, 0x40,
	0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6e, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x6e, 0x6e, 0x6f,
	0x75, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65,
	0x22, 0x12, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x3f, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x3e, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x77, 0x69, 0x74,
	0x63, 0x68, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x3f, 0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x63, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x16, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x41,
	0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x17,
	0x0a, 0x15, 0x54, 0x72, 0x61, 0x63, 0x6b, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x72, 0x0a, 0x09, 0x42, 0x75, 0x73, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x73, 0x12, 0x1f, 0x0a, 0x1b, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x53, 0x54, 0x41,
	0x52, 0x5f, 0x54, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x21, 0x0a, 0x1d, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x53, 0x54,
	0x41, 0x52, 0x5f, 0x54, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x52,
	0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x21, 0x0a, 0x1d, 0x54, 0x52, 0x41, 0x43,
	0x4b, 0x53, 0x54, 0x41, 0x52, 0x5f, 0x54, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x48, 0x41,
	0x54, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x41, 0x4e, 0x44, 0x10, 0x02, 0x2a, 0xc6, 0x01, 0x0a, 0x12,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x28, 0x0a, 0x24, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x53, 0x54, 0x41, 0x52, 0x5f,
	0x54, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x46,
	0x49, 0x47, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x00, 0x12, 0x29, 0x0a, 0x25,
	0x54, 0x52, 0x41, 0x43, 0x4b, 0x53, 0x54, 0x41, 0x52, 0x5f, 0x54, 0x57, 0x49, 0x54, 0x43, 0x48,
	0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x47, 0x45, 0x54,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x01, 0x12, 0x2c, 0x0a, 0x28, 0x54, 0x52, 0x41, 0x43, 0x4b,
	0x53, 0x54, 0x41, 0x52, 0x5f, 0x54, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x48, 0x41, 0x54,
	0x5f, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x5f, 0x41, 0x4e, 0x4e, 0x4f, 0x55, 0x4e, 0x43, 0x45, 0x5f,
	0x52, 0x45, 0x51, 0x10, 0x02, 0x12, 0x2d, 0x0a, 0x29, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x53, 0x54,
	0x41, 0x52, 0x5f, 0x54, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x54,
	0x52, 0x41, 0x43, 0x4b, 0x5f, 0x41, 0x4e, 0x4e, 0x4f, 0x55, 0x4e, 0x43, 0x45, 0x5f, 0x52, 0x45,
	0x53, 0x50, 0x10, 0x03, 0x2a, 0x90, 0x01, 0x0a, 0x12, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x25, 0x0a, 0x21, 0x54,
	0x52, 0x41, 0x43, 0x4b, 0x53, 0x54, 0x41, 0x52, 0x5f, 0x54, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f,
	0x43, 0x48, 0x41, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x28, 0x0a, 0x24, 0x54, 0x52, 0x41, 0x4b, 0x43, 0x53, 0x54, 0x41, 0x52, 0x5f,
	0x54, 0x57, 0x49, 0x54, 0x43, 0x48, 0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x46,
	0x49, 0x47, 0x5f, 0x53, 0x45, 0x54, 0x5f, 0x52, 0x45, 0x51, 0x10, 0x01, 0x12, 0x29, 0x0a, 0x25,
	0x54, 0x52, 0x41, 0x4b, 0x43, 0x53, 0x54, 0x41, 0x52, 0x5f, 0x54, 0x57, 0x49, 0x54, 0x43, 0x48,
	0x5f, 0x43, 0x48, 0x41, 0x54, 0x5f, 0x43, 0x4f, 0x4e, 0x46, 0x49, 0x47, 0x5f, 0x53, 0x45, 0x54,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x10, 0x02, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f, 0x75, 0x73,
	0x6b, 0x6f, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x72, 0x2f, 0x74, 0x77,
	0x69, 0x74, 0x63, 0x68, 0x63, 0x68, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_twitchchat_proto_rawDescOnce sync.Once
	file_twitchchat_proto_rawDescData = file_twitchchat_proto_rawDesc
)

func file_twitchchat_proto_rawDescGZIP() []byte {
	file_twitchchat_proto_rawDescOnce.Do(func() {
		file_twitchchat_proto_rawDescData = protoimpl.X.CompressGZIP(file_twitchchat_proto_rawDescData)
	})
	return file_twitchchat_proto_rawDescData
}

var file_twitchchat_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_twitchchat_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_twitchchat_proto_goTypes = []any{
	(BusTopics)(0),                // 0: twitchchat.BusTopics
	(MessageTypeRequest)(0),       // 1: twitchchat.MessageTypeRequest
	(MessageTypeCommand)(0),       // 2: twitchchat.MessageTypeCommand
	(*Config)(nil),                // 3: twitchchat.Config
	(*ConfigGetRequest)(nil),      // 4: twitchchat.ConfigGetRequest
	(*ConfigGetResponse)(nil),     // 5: twitchchat.ConfigGetResponse
	(*ConfigSetRequest)(nil),      // 6: twitchchat.ConfigSetRequest
	(*ConfigSetResponse)(nil),     // 7: twitchchat.ConfigSetResponse
	(*TrackAnnounceRequest)(nil),  // 8: twitchchat.TrackAnnounceRequest
	(*TrackAnnounceResponse)(nil), // 9: twitchchat.TrackAnnounceResponse
}
var file_twitchchat_proto_depIdxs = []int32{
	3, // 0: twitchchat.ConfigGetResponse.config:type_name -> twitchchat.Config
	3, // 1: twitchchat.ConfigSetRequest.config:type_name -> twitchchat.Config
	3, // 2: twitchchat.ConfigSetResponse.config:type_name -> twitchchat.Config
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_twitchchat_proto_init() }
func file_twitchchat_proto_init() {
	if File_twitchchat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_twitchchat_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitchchat_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitchchat_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitchchat_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitchchat_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ConfigSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitchchat_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TrackAnnounceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_twitchchat_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TrackAnnounceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_twitchchat_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_twitchchat_proto_goTypes,
		DependencyIndexes: file_twitchchat_proto_depIdxs,
		EnumInfos:         file_twitchchat_proto_enumTypes,
		MessageInfos:      file_twitchchat_proto_msgTypes,
	}.Build()
	File_twitchchat_proto = out.File
	file_twitchchat_proto_rawDesc = nil
	file_twitchchat_proto_goTypes = nil
	file_twitchchat_proto_depIdxs = nil
}
