// @generated by protoc-gen-es v1.10.0
// @generated from file trackstar.proto (package trackstar, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum trackstar.BusTopic
 */
export const BusTopic = /*@__PURE__*/ proto3.makeEnum(
  "trackstar.BusTopic",
  [
    {no: 0, name: "TRACKSTAR"},
  ],
);

/**
 * @generated from enum trackstar.MessageType
 */
export const MessageType = /*@__PURE__*/ proto3.makeEnum(
  "trackstar.MessageType",
  [
    {no: 0, name: "TYPE_UNSPECIFIED"},
    {no: 1, name: "TYPE_DECK_DISCOVERED"},
    {no: 2, name: "TYPE_TRACK_UPDATE"},
    {no: 3, name: "TYPE_DECK_STYLE_UPDATE"},
  ],
);

/**
 * @generated from message trackstar.DeckDiscovered
 */
export const DeckDiscovered = /*@__PURE__*/ proto3.makeMessageType(
  "trackstar.DeckDiscovered",
  () => [
    { no: 1, name: "deck_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message trackstar.TrackUpdate
 */
export const TrackUpdate = /*@__PURE__*/ proto3.makeMessageType(
  "trackstar.TrackUpdate",
  () => [
    { no: 1, name: "deck_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "track", kind: "message", T: Track },
  ],
);

/**
 * @generated from message trackstar.Track
 */
export const Track = /*@__PURE__*/ proto3.makeMessageType(
  "trackstar.Track",
  () => [
    { no: 1, name: "artist", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "title", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message trackstar.DeckStyleUpdate
 */
export const DeckStyleUpdate = /*@__PURE__*/ proto3.makeMessageType(
  "trackstar.DeckStyleUpdate",
  () => [
    { no: 1, name: "deck_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "style_field", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "style_value", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message trackstar.ConfigDeckStyle
 */
export const ConfigDeckStyle = /*@__PURE__*/ proto3.makeMessageType(
  "trackstar.ConfigDeckStyle",
  () => [
    { no: 1, name: "properties", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "scalar", T: 9 /* ScalarType.STRING */} },
  ],
);

/**
 * @generated from message trackstar.Config
 */
export const Config = /*@__PURE__*/ proto3.makeMessageType(
  "trackstar.Config",
  () => [
    { no: 1, name: "deck_ids", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "style", kind: "map", K: 9 /* ScalarType.STRING */, V: {kind: "message", T: ConfigDeckStyle} },
  ],
);

