// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: trackstar.proto

package trackstar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusTopic int32

const (
	BusTopic_TRACKSTAR BusTopic = 0
)

// Enum value maps for BusTopic.
var (
	BusTopic_name = map[int32]string{
		0: "TRACKSTAR",
	}
	BusTopic_value = map[string]int32{
		"TRACKSTAR": 0,
	}
)

func (x BusTopic) Enum() *BusTopic {
	p := new(BusTopic)
	*p = x
	return p
}

func (x BusTopic) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusTopic) Descriptor() protoreflect.EnumDescriptor {
	return file_trackstar_proto_enumTypes[0].Descriptor()
}

func (BusTopic) Type() protoreflect.EnumType {
	return &file_trackstar_proto_enumTypes[0]
}

func (x BusTopic) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusTopic.Descriptor instead.
func (BusTopic) EnumDescriptor() ([]byte, []int) {
	return file_trackstar_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_TYPE_UNSPECIFIED       MessageType = 0
	MessageType_TYPE_DECK_DISCOVERED   MessageType = 1
	MessageType_TYPE_TRACK_UPDATE      MessageType = 2
	MessageType_TYPE_DECK_STYLE_UPDATE MessageType = 3
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_DECK_DISCOVERED",
		2: "TYPE_TRACK_UPDATE",
		3: "TYPE_DECK_STYLE_UPDATE",
	}
	MessageType_value = map[string]int32{
		"TYPE_UNSPECIFIED":       0,
		"TYPE_DECK_DISCOVERED":   1,
		"TYPE_TRACK_UPDATE":      2,
		"TYPE_DECK_STYLE_UPDATE": 3,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_trackstar_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_trackstar_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_trackstar_proto_rawDescGZIP(), []int{1}
}

type DeckDiscovered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId string `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
}

func (x *DeckDiscovered) Reset() {
	*x = DeckDiscovered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trackstar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeckDiscovered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckDiscovered) ProtoMessage() {}

func (x *DeckDiscovered) ProtoReflect() protoreflect.Message {
	mi := &file_trackstar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckDiscovered.ProtoReflect.Descriptor instead.
func (*DeckDiscovered) Descriptor() ([]byte, []int) {
	return file_trackstar_proto_rawDescGZIP(), []int{0}
}

func (x *DeckDiscovered) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

type TrackUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeckId string `protobuf:"bytes,1,opt,name=deck_id,json=deckId,proto3" json:"deck_id,omitempty"`
	Track  *Track `protobuf:"bytes,2,opt,name=track,proto3" json:"track,omitempty"`
	When   int64  `protobuf:"varint,3,opt,name=when,proto3" json:"when,omitempty"`
}

func (x *TrackUpdate) Reset() {
	*x = TrackUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trackstar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrackUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackUpdate) ProtoMessage() {}

func (x *TrackUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_trackstar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackUpdate.ProtoReflect.Descriptor instead.
func (*TrackUpdate) Descriptor() ([]byte, []int) {
	return file_trackstar_proto_rawDescGZIP(), []int{1}
}

func (x *TrackUpdate) GetDeckId() string {
	if x != nil {
		return x.DeckId
	}
	return ""
}

func (x *TrackUpdate) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

func (x *TrackUpdate) GetWhen() int64 {
	if x != nil {
		return x.When
	}
	return 0
}

type Track struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Artist string `protobuf:"bytes,1,opt,name=artist,proto3" json:"artist,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *Track) Reset() {
	*x = Track{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trackstar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_trackstar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_trackstar_proto_rawDescGZIP(), []int{2}
}

func (x *Track) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

var File_trackstar_proto protoreflect.FileDescriptor

var file_trackstar_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x72, 0x22, 0x29, 0x0a, 0x0e,
	0x44, 0x65, 0x63, 0x6b, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x65, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x64, 0x65, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x62, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x6b, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x12,
	0x26, 0x0a, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x74, 0x61, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x63, 0x6b,
	0x52, 0x05, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x77, 0x68, 0x65, 0x6e, 0x22, 0x35, 0x0a, 0x05, 0x54,
	0x72, 0x61, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x72, 0x74, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x2a, 0x19, 0x0a, 0x08, 0x42, 0x75, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x53, 0x54, 0x41, 0x52, 0x10, 0x00, 0x2a, 0x70, 0x0a,
	0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x43, 0x4b, 0x5f,
	0x44, 0x49, 0x53, 0x43, 0x4f, 0x56, 0x45, 0x52, 0x45, 0x44, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x52, 0x41, 0x43, 0x4b, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54,
	0x45, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x44, 0x45, 0x43, 0x4b,
	0x5f, 0x53, 0x54, 0x59, 0x4c, 0x45, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x03, 0x42,
	0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75,
	0x74, 0x6f, 0x6e, 0x6f, 0x6d, 0x6f, 0x75, 0x73, 0x6b, 0x6f, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x73, 0x74, 0x61, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trackstar_proto_rawDescOnce sync.Once
	file_trackstar_proto_rawDescData = file_trackstar_proto_rawDesc
)

func file_trackstar_proto_rawDescGZIP() []byte {
	file_trackstar_proto_rawDescOnce.Do(func() {
		file_trackstar_proto_rawDescData = protoimpl.X.CompressGZIP(file_trackstar_proto_rawDescData)
	})
	return file_trackstar_proto_rawDescData
}

var file_trackstar_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_trackstar_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_trackstar_proto_goTypes = []any{
	(BusTopic)(0),          // 0: trackstar.BusTopic
	(MessageType)(0),       // 1: trackstar.MessageType
	(*DeckDiscovered)(nil), // 2: trackstar.DeckDiscovered
	(*TrackUpdate)(nil),    // 3: trackstar.TrackUpdate
	(*Track)(nil),          // 4: trackstar.Track
}
var file_trackstar_proto_depIdxs = []int32{
	4, // 0: trackstar.TrackUpdate.track:type_name -> trackstar.Track
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_trackstar_proto_init() }
func file_trackstar_proto_init() {
	if File_trackstar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trackstar_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DeckDiscovered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trackstar_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TrackUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trackstar_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Track); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trackstar_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trackstar_proto_goTypes,
		DependencyIndexes: file_trackstar_proto_depIdxs,
		EnumInfos:         file_trackstar_proto_enumTypes,
		MessageInfos:      file_trackstar_proto_msgTypes,
	}.Build()
	File_trackstar_proto = out.File
	file_trackstar_proto_rawDesc = nil
	file_trackstar_proto_goTypes = nil
	file_trackstar_proto_depIdxs = nil
}
