// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.3
// source: stagelinq.proto

package stagelinq

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BusTopics int32

const (
	BusTopics_STAGELINQ_STATE   BusTopics = 0
	BusTopics_STAGELINQ_CONTROL BusTopics = 1
)

// Enum value maps for BusTopics.
var (
	BusTopics_name = map[int32]string{
		0: "STAGELINQ_STATE",
		1: "STAGELINQ_CONTROL",
	}
	BusTopics_value = map[string]int32{
		"STAGELINQ_STATE":   0,
		"STAGELINQ_CONTROL": 1,
	}
)

func (x BusTopics) Enum() *BusTopics {
	p := new(BusTopics)
	*p = x
	return p
}

func (x BusTopics) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BusTopics) Descriptor() protoreflect.EnumDescriptor {
	return file_stagelinq_proto_enumTypes[0].Descriptor()
}

func (BusTopics) Type() protoreflect.EnumType {
	return &file_stagelinq_proto_enumTypes[0]
}

func (x BusTopics) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BusTopics.Descriptor instead.
func (BusTopics) EnumDescriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_TYPE_UNSPECIFIED               MessageType = 0
	MessageType_TYPE_CAPTURE_THRESHOLD_REQUEST MessageType = 1
	MessageType_TYPE_GET_THRESHOLD_REQUEST     MessageType = 2
	MessageType_TYPE_THRESHOLD_UPDATE          MessageType = 3
	MessageType_TYPE_GET_DEVICES_REQUEST       MessageType = 4
	MessageType_TYPE_GET_DEVICES_RESPONSE      MessageType = 5
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_CAPTURE_THRESHOLD_REQUEST",
		2: "TYPE_GET_THRESHOLD_REQUEST",
		3: "TYPE_THRESHOLD_UPDATE",
		4: "TYPE_GET_DEVICES_REQUEST",
		5: "TYPE_GET_DEVICES_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"TYPE_UNSPECIFIED":               0,
		"TYPE_CAPTURE_THRESHOLD_REQUEST": 1,
		"TYPE_GET_THRESHOLD_REQUEST":     2,
		"TYPE_THRESHOLD_UPDATE":          3,
		"TYPE_GET_DEVICES_REQUEST":       4,
		"TYPE_GET_DEVICES_RESPONSE":      5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_stagelinq_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_stagelinq_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{1}
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FaderThreshold float64 `protobuf:"fixed64,1,opt,name=fader_threshold,json=faderThreshold,proto3" json:"fader_threshold,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stagelinq_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_stagelinq_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetFaderThreshold() float64 {
	if x != nil {
		return x.FaderThreshold
	}
	return 0
}

type CaptureThresholdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CaptureThresholdRequest) Reset() {
	*x = CaptureThresholdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stagelinq_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureThresholdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureThresholdRequest) ProtoMessage() {}

func (x *CaptureThresholdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stagelinq_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureThresholdRequest.ProtoReflect.Descriptor instead.
func (*CaptureThresholdRequest) Descriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{1}
}

type ThresholdUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FaderThreshold float64 `protobuf:"fixed64,1,opt,name=fader_threshold,json=faderThreshold,proto3" json:"fader_threshold,omitempty"`
}

func (x *ThresholdUpdate) Reset() {
	*x = ThresholdUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stagelinq_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThresholdUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThresholdUpdate) ProtoMessage() {}

func (x *ThresholdUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_stagelinq_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThresholdUpdate.ProtoReflect.Descriptor instead.
func (*ThresholdUpdate) Descriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{2}
}

func (x *ThresholdUpdate) GetFaderThreshold() float64 {
	if x != nil {
		return x.FaderThreshold
	}
	return 0
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stagelinq_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_stagelinq_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{3}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip              string     `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Name            string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SoftwareName    string     `protobuf:"bytes,3,opt,name=software_name,json=softwareName,proto3" json:"software_name,omitempty"`
	SoftwareVerison string     `protobuf:"bytes,4,opt,name=software_verison,json=softwareVerison,proto3" json:"software_verison,omitempty"`
	Services        []*Service `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stagelinq_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_stagelinq_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{4}
}

func (x *Device) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Device) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Device) GetSoftwareName() string {
	if x != nil {
		return x.SoftwareName
	}
	return ""
}

func (x *Device) GetSoftwareVerison() string {
	if x != nil {
		return x.SoftwareVerison
	}
	return ""
}

func (x *Device) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetDevicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetDevicesRequest) Reset() {
	*x = GetDevicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stagelinq_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesRequest) ProtoMessage() {}

func (x *GetDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stagelinq_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesRequest.ProtoReflect.Descriptor instead.
func (*GetDevicesRequest) Descriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{5}
}

type GetDevicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Devices []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stagelinq_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stagelinq_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_stagelinq_proto_rawDescGZIP(), []int{6}
}

func (x *GetDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

var File_stagelinq_proto protoreflect.FileDescriptor

var file_stagelinq_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x6e, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x6e, 0x71, 0x22, 0x31, 0x0a, 0x06,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x27, 0x0a, 0x0f, 0x66, 0x61, 0x64, 0x65, 0x72, 0x5f,
	0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x0e, 0x66, 0x61, 0x64, 0x65, 0x72, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x22,
	0x19, 0x0a, 0x17, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x54, 0x68, 0x72, 0x65, 0x73, 0x68,
	0x6f, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x0f, 0x54, 0x68,
	0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x66, 0x61, 0x64, 0x65, 0x72, 0x5f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x66, 0x61, 0x64, 0x65, 0x72, 0x54, 0x68, 0x72,
	0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x22, 0x31, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0xac, 0x01, 0x0a, 0x06, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x6f, 0x66, 0x74,
	0x77, 0x61, 0x72, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a,
	0x10, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x69, 0x73, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x6f, 0x66, 0x74, 0x77, 0x61, 0x72,
	0x65, 0x56, 0x65, 0x72, 0x69, 0x73, 0x6f, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x61,
	0x67, 0x65, 0x6c, 0x69, 0x6e, 0x71, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x6e, 0x71,
	0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2a, 0x37, 0x0a, 0x09, 0x42, 0x75, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x13, 0x0a,
	0x0f, 0x53, 0x54, 0x41, 0x47, 0x45, 0x4c, 0x49, 0x4e, 0x51, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x47, 0x45, 0x4c, 0x49, 0x4e, 0x51, 0x5f,
	0x43, 0x4f, 0x4e, 0x54, 0x52, 0x4f, 0x4c, 0x10, 0x01, 0x2a, 0xbf, 0x01, 0x0a, 0x0b, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x22, 0x0a, 0x1e, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x43, 0x41, 0x50, 0x54, 0x55, 0x52, 0x45, 0x5f,
	0x54, 0x48, 0x52, 0x45, 0x53, 0x48, 0x4f, 0x4c, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x10, 0x01, 0x12, 0x1e, 0x0a, 0x1a, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f,
	0x54, 0x48, 0x52, 0x45, 0x53, 0x48, 0x4f, 0x4c, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x54, 0x48, 0x52, 0x45,
	0x53, 0x48, 0x4f, 0x4c, 0x44, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x1c,
	0x0a, 0x18, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43,
	0x45, 0x53, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x04, 0x12, 0x1d, 0x0a, 0x19,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x47, 0x45, 0x54, 0x5f, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x53,
	0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x05, 0x42, 0x2e, 0x5a, 0x2c, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x6e, 0x6f,
	0x6d, 0x6f, 0x75, 0x73, 0x6b, 0x6f, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x73, 0x74, 0x61,
	0x72, 0x2f, 0x73, 0x74, 0x61, 0x67, 0x65, 0x6c, 0x69, 0x6e, 0x71, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_stagelinq_proto_rawDescOnce sync.Once
	file_stagelinq_proto_rawDescData = file_stagelinq_proto_rawDesc
)

func file_stagelinq_proto_rawDescGZIP() []byte {
	file_stagelinq_proto_rawDescOnce.Do(func() {
		file_stagelinq_proto_rawDescData = protoimpl.X.CompressGZIP(file_stagelinq_proto_rawDescData)
	})
	return file_stagelinq_proto_rawDescData
}

var file_stagelinq_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stagelinq_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_stagelinq_proto_goTypes = []any{
	(BusTopics)(0),                  // 0: stagelinq.BusTopics
	(MessageType)(0),                // 1: stagelinq.MessageType
	(*Config)(nil),                  // 2: stagelinq.Config
	(*CaptureThresholdRequest)(nil), // 3: stagelinq.CaptureThresholdRequest
	(*ThresholdUpdate)(nil),         // 4: stagelinq.ThresholdUpdate
	(*Service)(nil),                 // 5: stagelinq.Service
	(*Device)(nil),                  // 6: stagelinq.Device
	(*GetDevicesRequest)(nil),       // 7: stagelinq.GetDevicesRequest
	(*GetDevicesResponse)(nil),      // 8: stagelinq.GetDevicesResponse
}
var file_stagelinq_proto_depIdxs = []int32{
	5, // 0: stagelinq.Device.services:type_name -> stagelinq.Service
	6, // 1: stagelinq.GetDevicesResponse.devices:type_name -> stagelinq.Device
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stagelinq_proto_init() }
func file_stagelinq_proto_init() {
	if File_stagelinq_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stagelinq_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stagelinq_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CaptureThresholdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stagelinq_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ThresholdUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stagelinq_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stagelinq_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stagelinq_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetDevicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stagelinq_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetDevicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stagelinq_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stagelinq_proto_goTypes,
		DependencyIndexes: file_stagelinq_proto_depIdxs,
		EnumInfos:         file_stagelinq_proto_enumTypes,
		MessageInfos:      file_stagelinq_proto_msgTypes,
	}.Build()
	File_stagelinq_proto = out.File
	file_stagelinq_proto_rawDesc = nil
	file_stagelinq_proto_goTypes = nil
	file_stagelinq_proto_depIdxs = nil
}
